import { EventBus } from "../EventBus";
import { Scene } from "phaser";

const TILE_WIDTH = 256;
const TILE_HEIGHT = 128;

export class Game extends Scene {
    camera: Phaser.Cameras.Scene2D.Camera;
    background: Phaser.GameObjects.Image;
    tileOutline: Phaser.GameObjects.Image;

    constructor() {
        super("Game");
    }

    create() {
        this.camera = this.cameras.main;

        this.drawTiles();
        this.tileOutline = this.add.image(0, 0, "tile-outline");
        EventBus.emit("current-scene-ready", this);
    }

    drawTiles() {
        const xStartPoint = 0;
        const yStartPoint = 0;

        // full map generated by server? Store and use JSON
        this.add.image(0, 0, "base_tiles");

        // for (let x = 0; x < this.xTiles; x++) {
        //     for (let y = 0; y < this.yTiles; y++) {
        //         // this.add.image(
        //         //     xStartPoint + this.plotSize,
        //         //     yStartPoint + this.plotSize,
        //         //     "base_tiles"
        //         // ).setOrigin(0, 0);
        //     }
        // }
    }

    update() {
        // CAMERA CONTROLS
        const scrollDelta = this.input.activePointer.deltaY;
        this.camera.zoom += scrollDelta * -0.0001;
        // Clamp the zoom factor to prevent excessive zooming
        this.camera.zoom = Phaser.Math.Clamp(this.camera.zoom, 0.25, 0.75);

        // TODO: Limit to game canvas (not navbar)
        if (this.input.activePointer.isDown) {
            this.camera.scrollX -= this.input.activePointer.velocity.x / 10;
            this.camera.scrollY -= this.input.activePointer.velocity.y / 10;
        }

        // const scrollSensitivity = 0.001; // Adjust sensitivity as needed

        // this.input.on(
        //     "wheel",
        //     (
        //         _pointer: any,
        //         _gameObjects: any,
        //         _deltaX: any,
        //         deltaY: number,
        //         _deltaZ: any
        //     ) => {
        //         const zoomChange = Math.sign(deltaY) * scrollSensitivity;
        //         this.camera.zoom -= zoomChange;
        //         console.log(this.camera.zoom);
        //     }
        // );

        // TILE HIGHLIGHT
        const worldPoint = this.cameras.main.getWorldPoint(
            this.input.x,
            this.input.y
        );

        this.tileOutline.x = Phaser.Math.Snap.To(
            worldPoint.x,
            TILE_WIDTH - TILE_HEIGHT
        );
        this.tileOutline.y = Phaser.Math.Snap.To(
            worldPoint.y,
            (TILE_WIDTH + TILE_HEIGHT) / 2
        );
    }
}
